---
- hosts: localhost
  become: true
  become_user: root
  become_method: ansible.builtin.sudo

  vars:
    kernel:
      default: arch-latest
      rootuuid: 7036bf75-ca61-4ff7-b0db-513143bb6edc
      ucode: intel-ucode
    base:
      extended: true 
      keymap: localectl set-keymap fr
      x11keymap: localectl set-x11-keymap fr pc105 azerty
    userapps:
      packages:
        - gdb,clang,lldb
        - heaptrack,lcov,perf,valgrind
        - jre-openjdk
        - keepassxc
        - pdfarranger
        - qemu,qemu-system-riscv,qemu-user-static-binfmt
        - riscv64-linux-gnu-gcc
      flatpaks:
        - com.valvesoftware.Steam

  tasks:
    - name: Fail if we are not on ivara
      ansible.builtin.fail: msg="This playbook is made to set up ivara only"
      when: ansible_hostname != "ivara"
    - {import_role: name=system tasks_from=kernel, tags: ['kernel']}
    - {import_role: name=system tasks_from=base, tags: ['base']}
    - {import_role: name=system tasks_from=gnome, tags: ['gnome']}
    - {import_role: name=system tasks_from=userapps, tags: ['userapps']}
