---
- hosts: localhost
  become: true
  become_user: root
  become_method: ansible.builtin.sudo

  vars:
    kernel:
      default: arch-lts
      rootuuid: 78da4ebd-5eba-4a7c-8caf-5f297eece0a7
      ucode: amd-ucode
      options: nvidia-drm.modeset=1
    base:
      extended: true
    keyboard:
      keymap: us-acentos
      xkblayout: us,fr
      xkbmodel: pc105
      xkbvariant: qwerty-fr,azerty
    userapps:
      packages:
        - darktable,shotwell
        - dotnet-runtime,dotnet-sdk,mono
        - thunderbird,thunderbird-i18n-fr 
        - gdb,clang,lldb
        - gnucash
        - heaptrack,lcov,perf,valgrind
        - helix,zed
        - inkscape
        - libxcrypt-compat  # Saleae Logic 2
        - jre-openjdk
        - keepassxc
        - kicad,kicad-library
        - pdfarranger
        - qemu,qemu-system-riscv,qemu-user-static-binfmt
        - quodlibet
        - riscv64-linux-gnu-gcc
        - zettlr
      flatpaks:
        - org.freac.freac
        - com.valvesoftware.Steam

  tasks:
    - name: Fail if we are not on nyx
      ansible.builtin.fail: msg="This playbook is made to set up nyx only"
      when: ansible_hostname != "nyx"
    - {import_role: name=system tasks_from=kernel, tags: ['kernel']}
    - {import_role: name=system tasks_from=base, tags: ['base']}
    - {import_role: name=system tasks_from=keyboard, tags: ['base', 'keyboard']}
    - {import_role: name=system tasks_from=nvidia, tags: ['nvidia']}
    - {import_role: name=system tasks_from=gnome, tags: ['gnome']}
    - {import_role: name=system tasks_from=userapps, tags: ['userapps']}
    - {import_role: name=system tasks_from=podman, tags: ['podman']}
    - {import_role: name=system tasks_from=hardening, tags: ['hardening']}
